<?php
require('routeros_api.class.php');

// Cek apakah request datang dari form POST
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $ip = $_POST['ip'];
    $port = (int)$_POST['port'];
    $username = $_POST['username'];
    $password = $_POST['password'];
    $dataType = $_POST['data_type'];

    $API = new RouterosAPI();
    $API->debug = false; // Set ke true jika ingin melihat debug output

    if ($API->connect($ip, $username, $password, $port)) {
        // Ambil data dari Mikrotik sesuai dataType yang dipilih
        $data = $API->comm($dataType . '/print');

        // Header file RSC
        $rscContent = "# Mikrotik configuration export\r\n";
        $rscContent .= "# Generated by PHP Native API Export App\r\n";
        $rscContent .= "# Date: " . date("Y-m-d H:i:s") . "\r\n\r\n";

        // Tambahkan perintah sesuai dataType
        switch ($dataType) {
            case '/ip/hotspot/user':
                $rscContent .= "/ip hotspot user\r\n";
                foreach ($data as $item) {
                    if (isset($item['.id'])) { // Pastikan ID ada untuk perintah set
                        $rscContent .= "add ";
                        if (isset($item['name'])) $rscContent .= "name=" . escapeshellarg($item['name']) . " ";
                        if (isset($item['password'])) $rscContent .= "password=" . escapeshellarg($item['password']) . " ";
                        if (isset($item['profile'])) $rscContent .= "profile=" . escapeshellarg($item['profile']) . " ";
                        if (isset($item['comment'])) $rscContent .= "comment=" . escapeshellarg($item['comment']) . " ";
                        // Tambahkan properti lain yang relevan
                        $rscContent .= "\r\n";
                    }
                }
                break;
            case '/ip/hotspot/user/profile':
                $rscContent .= "/ip hotspot user profile\r\n";
                foreach ($data as $item) {
                    if (isset($item['.id'])) {
                        $rscContent .= "add ";
                        if (isset($item['name'])) $rscContent .= "name=" . escapeshellarg($item['name']) . " ";
                        if (isset($item['idle-timeout'])) $rscContent .= "idle-timeout=" . escapeshellarg($item['idle-timeout']) . " ";
                        if (isset($item['keepalive-timeout'])) $rscContent .= "keepalive-timeout=" . escapeshellarg($item['keepalive-timeout']) . " ";
                        if (isset($item['status-autorefresh'])) $rscContent .= "status-autorefresh=" . escapeshellarg($item['status-autorefresh']) . " ";
                        if (isset($item['shared-users'])) $rscContent .= "shared-users=" . escapeshellarg($item['shared-users']) . " ";
                        if (isset($item['add-mac-cookie'])) $rscContent .= "add-mac-cookie=" . escapeshellarg($item['add-mac-cookie']) . " ";
                        if (isset($item['mac-cookie-timeout'])) $rscContent .= "mac-cookie-timeout=" . escapeshellarg($item['mac-cookie-timeout']) . " ";
                        if (isset($item['rate-limit'])) $rscContent .= "rate-limit=" . escapeshellarg($item['rate-limit']) . " ";
                        if (isset($item['address-list'])) $rscContent .= "address-list=" . escapeshellarg($item['address-list']) . " ";
                        if (isset($item['transparent-proxy'])) $rscContent .= "transparent-proxy=" . escapeshellarg($item['transparent-proxy']) . " ";
                        if (isset($item['session-timeout'])) $rscContent .= "session-timeout=" . escapeshellarg($item['session-timeout']) . " "; // Added based on your example
                        if (isset($item['comment'])) $rscContent .= "comment=" . escapeshellarg($item['comment']) . " ";
                        $rscContent .= "\r\n";
                    }
                }
                break;
            case '/ppp/secret': // === KASUS BARU UNTUK PPP SECRET ===
                $rscContent .= "/ppp secret\r\n";
                foreach ($data as $item) {
                    if (isset($item['.id'])) {
                        $rscContent .= "add ";
                        // Tambahkan properti yang relevan
                        if (isset($item['name'])) $rscContent .= "name=" . escapeshellarg($item['name']) . " ";
                        if (isset($item['password'])) {
                            // Perlakuan khusus untuk password: jika ada karakter khusus, harus diapit kutip ganda dan escape
                            $escapedPassword = str_replace(['\\', '"', '$'], ['\\\\', '\"', '\$'], $item['password']);
                            $rscContent .= 'password="' . $escapedPassword . '" ';
                        }
                        if (isset($item['service'])) $rscContent .= "service=" . escapeshellarg($item['service']) . " ";
                        if (isset($item['profile'])) $rscContent .= "profile=" . escapeshellarg($item['profile']) . " ";
                        if (isset($item['local-address'])) $rscContent .= "local-address=" . escapeshellarg($item['local-address']) . " ";
                        if (isset($item['remote-address'])) $rscContent .= "remote-address=" . escapeshellarg($item['remote-address']) . " ";
                        if (isset($item['comment'])) $rscContent .= "comment=" . escapeshellarg($item['comment']) . " ";
                        // Tambahkan properti lain yang mungkin relevan, seperti disabled, dll.
                        if (isset($item['disabled']) && $item['disabled'] == 'true') $rscContent .= "disabled=yes ";
                        // Properti lain yang tidak umum di export seperti caller-id, last-logged-out, dll, biasanya diabaikan

                        $rscContent .= "\r\n";
                    }
                }
                break;
            case '/ppp/profile':
                $rscContent .= "/ppp profile\r\n";
                foreach ($data as $item) {
                    if (isset($item['.id'])) {
                        $rscContent .= "add ";
                        if (isset($item['name'])) $rscContent .= "name=" . escapeshellarg($item['name']) . " ";
                        if (isset($item['local-address'])) $rscContent .= "local-address=" . escapeshellarg($item['local-address']) . " ";
                        if (isset($item['remote-address'])) $rscContent .= "remote-address=" . escapeshellarg($item['remote-address']) . " ";
                        if (isset($item['bridge-learning'])) $rscContent .= "bridge-learning=" . escapeshellarg($item['bridge-learning']) . " ";
                        if (isset($item['use-ipv6'])) $rscContent .= "use-ipv6=" . escapeshellarg($item['use-ipv6']) . " ";
                        if (isset($item['use-mpls'])) $rscContent .= "use-mpls=" . escapeshellarg($item['use-mpls']) . " ";
                        if (isset($item['use-compression'])) $rscContent .= "use-compression=" . escapeshellarg($item['use-compression']) . " ";
                        if (isset($item['use-encryption'])) $rscContent .= "use-encryption=" . escapeshellarg($item['use-encryption']) . " ";
                        if (isset($item['only-one'])) $rscContent .= "only-one=" . escapeshellarg($item['only-one']) . " ";
                        if (isset($item['change-tcp-mss'])) $rscContent .= "change-tcp-mss=" . escapeshellarg($item['change-tcp-mss']) . " ";
                        if (isset($item['use-upnp'])) $rscContent .= "use-upnp=" . escapeshellarg($item['use-upnp']) . " ";
                        if (isset($item['rate-limit'])) $rscContent .= "rate-limit=" . escapeshellarg($item['rate-limit']) . " ";
                        if (isset($item['address-list'])) $rscContent .= "address-list=" . escapeshellarg($item['address-list']) . " ";
                        if (isset($item['dns-server'])) $rscContent .= "dns-server=" . escapeshellarg($item['dns-server']) . " ";
                        if (isset($item['on-up'])) $rscContent .= "on-up=" . escapeshellarg($item['on-up']) . " ";
                        if (isset($item['on-down'])) $rscContent .= "on-down=" . escapeshellarg($item['on-down']) . " ";
                        if (isset($item['comment'])) $rscContent .= "comment=" . escapeshellarg($item['comment']) . " ";
                        $rscContent .= "\r\n";
                    }
                }
                break;
            default:
                // Untuk jenis data yang tidak spesifik, coba format umum
                $rscContent .= $dataType . "\r\n";
                foreach ($data as $item) {
                    if (isset($item['.id'])) {
                        $rscContent .= "add ";
                        foreach ($item as $key => $value) {
                            // Hindari ID internal, data array, dan properti status/informasi
                            $excludeKeys = ['.id', 'last-logged-out', 'last-caller-id', 'last-disconnect-reason', 'bytes-in', 'bytes-out', 'packets-in', 'packets-out', 'dynamic', 'running'];
                            if (!in_array($key, $excludeKeys) && !is_array($value)) {
                                // Penanganan khusus untuk password
                                if ($key === 'password') {
                                    $escapedValue = str_replace(['\\', '"', '$'], ['\\\\', '\"', '\$'], $value);
                                    $rscContent .= $key . '="' . $escapedValue . '" ';
                                } else {
                                    $rscContent .= $key . "=" . escapeshellarg($value) . " ";
                                }
                            }
                        }
                        $rscContent .= "\r\n";
                    }
                }
                break;
        }

        $API->disconnect();

        // Siapkan untuk download file .rsc
        $filename = str_replace('/', '_', trim($dataType, '/')) . "_" . date("Ymd_His") . ".rsc";
        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . strlen($rscContent));
        echo $rscContent;
        exit;
    } else {
        $errorMessage = $API->error_str ? $API->error_str : "Koneksi ke Mikrotik gagal. Pastikan IP, Port, Username, dan Password benar.";
        header('Location: index.php?status=error&message=' . urlencode($errorMessage));
        exit;
    }
} else {
    // Jika akses langsung ke export.php tanpa POST request
    header('Location: index.php?status=error&message=' . urlencode('Akses tidak diizinkan. Silakan gunakan form.'));
    exit;
}
